# config.yml
# Configuration file for OMEN project

# Path to the sample features matrix (sf_mat.npy)
sample_features_path: /home/krastega0/OMEN/tests/sf_mat.npy

# Path to the neighbor matrix (A_mat.npy)
neighbor_matrix_path: /home/krastega0/OMEN/tests/A_mat.npy

# Path to the coordinates Excel file (coords_brain.xlsx)
coords_path: /home/krastega0/OMEN/tests/coords_brain.xlsx