# This workflow will build and publish your Python package to TestPyPI using a classic API token stored in GitHub Secrets.
# Make sure you have added TEST_PYPI_API_TOKEN as a secret in your repository.

name: Upload Python Package to TestPyPI

on:
  push:
    branches:
      - main
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install build tools
        run: python -m pip install build twine
      - name: Build package
        run: python -m build
      - name: Publish to TestPyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: python3 -m twine upload --repository testpypi dist/* --verbose
